name: tutorial_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  injectable_generator: ^2.4.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
