name: tutorial_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: 
  injectable: 
  get_it:
  json_annotation:
  flutter_bloc:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed:
  build_runner:
  json_serializable:
  injectable_generator:

flutter:
  uses-material-design: true
